name: Create release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release
        type: string
        required: true

jobs:
  prepare-release:
    name: Prepare release
    uses: OHSU-OCTRI/shared-workflows/.github/workflows/node-release.yaml@main
    with:
      version: ${{ inputs.version }}
      node_version: '24.x'
      update_major_version_tag: true
